//Authentication
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOAD_USER = "LOAD_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOADING_STOP = "LOADING_STOP";
export const LOGOUT_USER = "LOGOUT_USER";

//Ondemand
export const GET_ON_DEMAND_DATA = "GET_ON_DEMAND_DATA";
export const GET_HOME_FIRST_SECTION = "GET_HOME_FIRST_SECTION";
export const GET_VIDEO_VIEW = "GET_VIDEO_VIEW";
export const GET_VIDEO_VIEW_SECOND = "GET_VIDEO_VIEW_SECOND";
export const GET_CATEGORY_VIDEOS = "GET_CATEGORY_VIDEOS";
export const GET_MY_WISH_LIST = "GET_MY_WISH_LIST";
export const GET_CATEGORIES = "GET_CATEGORIES";
