//Authentication
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOAD_USER = "LOAD_USER";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOADING_STOP = "LOADING_STOP";
export const LOGOUT_USER = "LOGOUT_USER";

//Subscription
export const SET_SUBSCRIPTION_PLAN = "SET_SUBSCRIPTION_PLAN";
export const GET_SUBSCRIPTION_PLANS = "GET_SUBSCRIPTION_PLANS";
export const SUBSCRIPTION_FAIL = "SUBSCRIPTION_FAIL";
export const PAYMENT_ADD_CARD = "PAYMENT_ADD_CARD";
export const REGISTER_SUBSCRIPTION_SUCCESS = "REGISTER_SUBSCRIPTION_SUCCESS";
//Ondemand
export const GET_ON_DEMAND_DATA = "GET_ON_DEMAND_DATA";
export const GET_HOME_FIRST_SECTION = "GET_HOME_FIRST_SECTION";
export const GET_VIDEO_VIEW = "GET_VIDEO_VIEW";
export const GET_VIDEO_VIEW_SECOND = "GET_VIDEO_VIEW_SECOND";
export const GET_CATEGORY_VIDEOS = "GET_CATEGORY_VIDEOS";
export const GET_MY_WISH_LIST = "GET_MY_WISH_LIST";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SINGLE_VIDEO = "GET_SINGLE_VIDEO";
export const CHANGE_IS_LOADING = "CHANGE_IS_LOADING";
export const SELECT_VIDEO = "SELECT_VIDEO";
export const GET_SINGLE_CATEGORY_VIDEOS = "GET_SINGLE_CATEGORY_VIDEOS";

//profiles
export const GET_SUB_PROFILES_SUCCESS = "GET_SUB_PROFILES_SUCCESS";
export const SET_CURRENT_SUB_PROFILE = "SET_CURRENT_SUB_PROFILE";
export const UPDATE_SUB_PROFILE_ID = "UPDATE_SUB_PROFILE_ID";

//Radio
export const GET_RADIO_DATA_SUCCESS = "GET_RADIO_DATA_SUCCESS";
export const GET_RADIO_DATA_FAIL = "GET_RADIO_DATA_FAIL";
export const GET_RADIO_DATA_PENDING = "GET_RADIO_DATA_PENDING";

//Get search resualts.
export const GET_SEARCH_RES = "GET_SEARCH_RES";
